spring:
  datasource:
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
