version: '3.7'
services:
  mysql_container:
    image: mysql:latest
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=certi
      - MYSQL_USER=certi
      - MYSQL_PASSWORD=certi
      - MYSQL_DATABASE=certi
  authentication:
    container_name: authentication
    build:
      context: $root/server/authentication
      dockerfile: $root/server/authentication/Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://${mysqlIp}/certi
      - spring.datasource.username=certi
      - spring.datasource.password=certi
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql_container

